services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Gcromo\:
    resource: '../src/*'
    exclude: '../src/Resources/**'

  Gcromo\Controller\Admin\BudgetController:
    public: true
    tags:
      - { name: controller.service_arguments }
